# Generated by Django 4.2.20 on 2025-03-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cli_nome",
                    models.CharField(max_length=100, verbose_name="Nome de Cliente"),
                ),
                ("cli_email", models.CharField(max_length=100, verbose_name="E-mail")),
                (
                    "cli_telefone",
                    models.CharField(max_length=20, verbose_name="Número de Telefone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pro_nome",
                    models.CharField(max_length=100, verbose_name="Nome de Produto"),
                ),
                (
                    "pro_descricao",
                    models.CharField(
                        max_length=1000, verbose_name="Descrição de Produto"
                    ),
                ),
                (
                    "pro_preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço de Produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ped_data", models.DateTimeField(verbose_name="Data do Pedido")),
                (
                    "ped_id_clientes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.clientes",
                    ),
                ),
                (
                    "ped_id_produtos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.produtos",
                    ),
                ),
            ],
        ),
    ]
